services:
    web:
        image: nginx:stable-alpine-slim
        container_name: go-tickets-nginx
        ports:
         - 80:80
        volumes:
         - ./docker/nginx/:/etc/nginx/conf.d/
         - ./:/var/www
        networks:
         - xnign-stekcit-go
    
    # go-tickets-front:
    #     image: node:latest

    go-titckes-back:
        image: php:8.0.2-fpm
        container_name: go-tickets-back
        volumes:
         - ./:/var/www
        networks:
         - xnign-stekcit-go
        
networks:
  xnign-stekcit-go:
    driver: bridge